	$(document).ready(function(){
		$('#nav-icon4').click(function(){
			$(this).toggleClass('open');
		});
	});
			$(document).ready(function(){
		$('#nav-icon4').click(function(){
			$(this).toggleClass('close');
		});
	});